/**
 * portfolio-bot — RAG chatbot grounded on atifali.pages.dev content.
 *
 * Phase 0: Cloudflare Worker scaffold with Workers AI + Vectorize bindings.
 *          Returns hello-world on /, basic health JSON on /health.
 *
 * Phase 1+ will add the ingestion pipeline, /chat endpoint with retrieval
 * and streaming, citation tracking, embeddable widget, and rate limiting.
 */

// Env interface comes from worker-configuration.d.ts (generated by `wrangler types`).
// Re-run `npm run cf-typegen` after editing wrangler.toml.

const CORS_HEADERS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "content-type",
} as const;

function jsonResponse(body: unknown, init: ResponseInit = {}): Response {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: {
      "content-type": "application/json",
      ...CORS_HEADERS,
      ...(init.headers ?? {}),
    },
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return jsonResponse({
        status: "ok",
        phase: 0,
        bindings: {
          ai: typeof env.AI !== "undefined",
          vector_index: typeof env.VECTOR_INDEX !== "undefined",
        },
      });
    }

    if (url.pathname === "/") {
      return new Response(
        "portfolio-bot Phase 0 scaffold. Try GET /health for binding status.\n",
        {
          headers: {
            "content-type": "text/plain",
            ...CORS_HEADERS,
          },
        },
      );
    }

    return jsonResponse({ error: "not_found", path: url.pathname }, { status: 404 });
  },
} satisfies ExportedHandler<Env>;
